[package]
name = "hm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
itertools = "0.11.0"
rpds = "1.0.0"
rustyline = "12.0.0"
